fix DeadLock
pocoproject/poco pull request #2875
Opened 2020-01-01 07:32 UTC by imtnd

> fix a dead lock when called unregisterConnector twice in same time.
> 
> lock 1:
> When socket connected:
> NObserver::notify(Notification* pNf) <- lock
> SocketConnector::onWritable(WritableNotification* pNotification)
> SocketConnector::onConnect()
> SocketConnector::unregisterConnector()
> SocketReactor::removeEventHandler(const Socket& socket, const Poco::AbstractObserver& observer) <- wait to unlock
> 
> When delete SocketConnector:
> SocketConnector::~SocketConnector()
> SocketConnector::unregisterConnector() <- lock
> SocketReactor::removeEventHandler(const Socket& socket, const Poco::AbstractObserver& observer)
> SocketNotifier::removeObserver(SocketReactor* pReactor, const Poco::AbstractObserver& observer)
> NotificationCenter::removeObserver(const AbstractObserver& observer)
> NObserver::disable() <- wait to unlock
> 
> Test code maybe execute only on my machine.
> I will remove test code if you don't need it.
> 

from #2874 .
It changed source and destination branch.

2022-06-02 05:35 UTC, aleks-f requested changes
please redirect to devel branch

2022-06-02 05:35 UTC, aleks-f commented on Net/testsuite/src/SocketConnectorTest.cpp
> +		void do_something(){
naming style

2022-06-02 05:39 UTC, aleks-f commented
@imtnd  this was likely fixed by https://github.com/pocoproject/poco/commit/f6de0cd3f490e1bf65b0d4faa9e09e5138b61103

It would be good to only add tests, mutex locking not needed

2022-06-02 17:04 UTC, closed without merging

2022-06-08 14:21 UTC, imtnd commented
Thank you for reviewing my code and closing this PR.