Allow using `Poco::FileStream` to wrap arbitrary file handles/descriptors as C++ streams
pocoproject/poco pull request #3444
Opened 2021-10-25 11:26 UTC by dgrunwald

In our application we open files in Python code, pass the file handle/descriptor to C++ code, and then use `FileStream` to access the file from C++. It's also possible for Python to pass a duplicate of the stdin handle to C++, so we need to handle the `ERROR_BROKEN_PIPE` special case.

2022-05-29 02:35 UTC, aleks-f commented
@dgrunwald please redirect this to devel branch

2022-05-29 14:18 UTC, aleks-f requested changes

2022-05-29 14:18 UTC, aleks-f commented on Foundation/include/Poco/FileStream.h
> +	void open_handle(NativeHandle handle, std::ios::openmode mode);
code style - this should be named `openHandle`

2023-06-10 03:45 UTC, aleks-f approved these changes

2024-01-29 21:38 UTC, matejk commented
I rebased this PR on latest devel and created new PR (#4424).

2024-04-05 13:19 UTC, closed without merging