MongoDB replica set uri support
pocoproject/poco pull request #3868
Opened 2022-11-11 09:53 UTC by artem-yadr

While working with Poco, I noticed that there is no way to connect to a MongoDB cluster using a replica set uri. Here I made basic support for mongodb replica set uri(uri with host:port enumiration) and readPreference option.

2022-11-12 03:21 UTC, aleks-f requested changes

2022-11-12 03:21 UTC, aleks-f commented on MongoDB/src/Connection.cpp
> +    std::string new_uri;
naming convention

2022-11-14 08:59 UTC, artem-yadr commented on MongoDB/src/Connection.cpp
> +    std::string new_uri;
fixed it

2023-01-25 23:36 UTC, artem-yadr commented
@aleks-f any comments about pr? I made the requested changes but have not received a response.

2023-02-02 10:31 UTC, closed without merging