Add ability to pass additional compiler settings via powershell build script
pocoproject/poco pull request #4097
Opened 2023-07-25 22:33 UTC by chrisbednarski

I needed to build poco with a custom struct alignment

Added ability to pass additional compiler options to the powershell script

Tested the build process both with and without passing extra compiler options.

Example PS command:
```
$env:CL = "/DWINDOWS_IGNORE_PACKING_MISMATCH"
.\buildwin.ps1 -poco_base . -vs 170 -action build -linkmode all -config both -platform Win32 -omit "Data/MySQL,Data/PostgreSQL" -openssl_base C:\OpenSSL -verbosity normal -compiler_options /Zp1
```

2023-09-24 00:29 UTC, aleks-f requested changes
- [ ] please clean up these redundant commits by syncing with the current devel branch
- [ ] these additional options should be added to earlier versions VS projects (or at least for vs160, and document that the parameter is no-op for earlier versions)

2023-10-22 06:42 UTC, chrisbednarski commented
rebased with devel branch

2023-10-22 07:05 UTC, chrisbednarski commented
* [x]  cleaned up redundant commits by syncing with the current devel branch
* [x]  additional options added to earlier versions VS projects (vs140-vs160)

2023-10-22 07:14 UTC, aleks-f commented
@chrisbednarski there's a [VS2022 projects issue on ARM](https://github.com/pocoproject/poco/issues/4207), so your effort will have to be coordinated with that. Also, in 2022, we should set C++17 as default. Please see if @hmartinez82 will fix that, or you can take care of that issue yourself as a part of this pull

2023-10-22 08:22 UTC, aleks-f commented
@chrisbednarski also, bear in mind that these may get overwritten in the future if someone regenerates them using [ProGen](https://github.com/pocoproject/poco/tree/devel/ProGen), so this change should be added there as well

2023-11-19 06:17 UTC, chrisbednarski commented
rebased with devel branch

2023-11-22 03:40 UTC, aleks-f requested changes

2023-11-22 03:40 UTC, aleks-f commented on Data/Data_vs170.vcxproj
> +      <AdditionalOptions>$(AdditionalCompilerOptions)</AdditionalOptions>
@chrisbednarski all of these `AdditionalOptions` for vs160 and 170 are redundant;
https://github.com/pocoproject/poco/blob/4a9285c997234bc216657ec8f1ce1b23b66fd223/Data/Data_vs170.vcxproj#L348

vs140 and 150 will be [removed](https://github.com/pocoproject/poco/issues/4274) for 1.13.0 release

2024-02-05 20:18 UTC, closed without merging