added new memeber SqlState to PostgreSQLException and made use of it.
pocoproject/poco pull request #4099
Opened 2023-07-27 08:30 UTC by omerbrandis

added support for SqlState in data::poco::postgresql.

----------------------------------------------------------------------
tested locally against postgresql 15.3.
was not able to find a suitable "location" for adding a "test" to the repo.

---------------------------------------------------------------------

tried to make it as simple as I could:

added a data member _SqlState to PostgreSQLException, 
added a getter SqlState(), 
added ctor  PostgreSQLException(const std::string& aMessage,**const char * pAnSqlState**);

added ctor StatementException::StatementException(const std::string& aMessage,**const char* pAnSqlState**);

modified StatementExecutor::prepare & StatementExecutor::execute(),
to make use of the new ctor for StatementException, such that the SqlState will be made available to the catcher of the exception.

:-)

2023-09-11 12:00 UTC, aleks-f commented
@omerbrandis can you please write a test case for this?

2023-09-11 12:45 UTC, omerbrandis commented
Dear alexks-f.

Can you please provide some instruction (or a reference to documentation about ) as to where/how to add a test for this 
repo and how to execute it?
( as mentioned before, I did not find information about this , I was unable to do it ( not unwilling )).

thanks,
Omer.

2023-09-11 13:59 UTC, aleks-f commented
@omerbrandis tests are [here](https://github.com/pocoproject/poco/blob/3eb18502e7b3adf3014eb5d3c5af2376908bc79b/Data/PostgreSQL/testsuite/src/PostgreSQLTest.cpp#L1224)

2023-09-12 11:37 UTC, omerbrandis commented
Hello @aleks-f 

I suggest the following test :
void PostgreSQLTest::testSqlState()
{
        if (!_pSession) fail ("Test not available.");

        try
        {
	    *_pSession << "syntax error", now;
        }
	catch (const Poco::Data::PostgreSQL::PostgreSQLException & Except)
	{
        	assertTrue(Except.SqlState() == std::string("42601"));    
        }
}

can you have a look, tell me if it seems sufficient or otherwise.
if so, i'll find how to add this to the original pull request or open a new one.

thanks,
Omer.

2023-09-13 09:05 UTC, omerbrandis commented
Hello @aleks-f

I've tested the new test on my machine.
i've pushed the new commit to my fork
it appears here in the pull request, so i've made no additional changes to the pull request and have not created a new one.

if there's anything else I should do , plz let me know.
:-)

2023-09-13 20:40 UTC, aleks-f requested changes

2023-09-13 20:40 UTC, aleks-f commented on Data/PostgreSQL/include/Poco/Data/PostgreSQL/PostgreSQLException.h
> +	char _SqlState[6];
naming convention - this is not how we name member variables

2023-09-13 20:40 UTC, aleks-f commented on Data/PostgreSQL/include/Poco/Data/PostgreSQL/PostgreSQLException.h
> +                /// Returns the SqlState
tabs, not spaces for indentation

2023-09-13 20:40 UTC, aleks-f commented on Data/PostgreSQL/testsuite/src/PostgreSQLTest.cpp
> +	    *_pSession << "syntax error", now;
tabs please

2023-09-13 20:42 UTC, aleks-f commented
https://github.com/pocoproject/poco/blob/devel/CONTRIBUTING.md

2023-09-14 05:29 UTC, omerbrandis commented
Hello @aleks-f

I've pushed new version.

Sorry for the naming issues, 
(I did review the contribution guidelines before starting on this path, but obviously did not do a good job of it ).

I also fixed a  bug that did not appear previously. 

hope that's everything,
and if not I'll happily fix the rest...

thanks,
Omer.

2023-10-20 15:44 UTC, merged