add visitor pattern implementation for Poco::Dynamic::Var
pocoproject/poco pull request #4144
Opened 2023-09-09 12:26 UTC by bas524

Complimentary for #2291
It's a simple implementation of runtime visitor
Main idea is using unique handler for every type which can be saved in the Dynamic::Var

As handler you can use lambda, std::function and function pointer with signature:
```cpp
std::function<void(const T&)>;
void (*)(const T &);
```

example
```cpp
// ...
Visitor visitor;
visitor.addHandler<std::string>([](const std::string& s) { std::cout << s; });
// ...
Poco::Dynamic::Var v = getVar();
if (visitor.visit(v))
{
    // successfully processed
}
```

2023-10-16 18:59 UTC, aleks-f requested changes
@bas524 we need that CI passing. rebase your branch with `devel` to get the most recent changes and I will restart any failing CI (sometimes they just timeout) that does not show a serious bug

2023-10-16 18:59 UTC, aleks-f commented on Foundation/include/Poco/Dynamic/VarVisitor.h
> +										Details::HandlerCaller([handler = f](const Poco::Dynamic::Var& x)
too much indent (3 is enough)

2023-10-16 18:59 UTC, aleks-f commented on Foundation/include/Poco/Dynamic/VarVisitor.h
> +										Details::HandlerCaller([handlerPointer = f](const Poco::Dynamic::Var& x)
too much indent (3 is enough)

2023-10-16 18:59 UTC, aleks-f commented on Foundation/src/VarVisitor.cpp
> +	bool wasHendled = false;
spelling, wasHandled, not hendled

2023-10-16 18:59 UTC, aleks-f commented on Foundation/testsuite/src/VarTest.cpp
> +	void operator()(const Dummy &d) {
style

2023-10-22 14:45 UTC, bas524 commented on Foundation/testsuite/src/VarTest.cpp
> +	void operator()(const Dummy &d) {
done

2023-10-22 14:45 UTC, bas524 commented on Foundation/src/VarVisitor.cpp
> +	bool wasHendled = false;
done

2023-10-22 14:46 UTC, bas524 commented on Foundation/include/Poco/Dynamic/VarVisitor.h
> +										Details::HandlerCaller([handlerPointer = f](const Poco::Dynamic::Var& x)
done

2023-10-22 14:46 UTC, bas524 commented on Foundation/include/Poco/Dynamic/VarVisitor.h
> +										Details::HandlerCaller([handler = f](const Poco::Dynamic::Var& x)
done

2023-11-11 18:18 UTC, merged