Merge DNSSD into main Poco
pocoproject/poco pull request #4323
Opened 2023-12-05 15:28 UTC by soroshsabz

ITNOA

Merge DNSSD into main Poco project

fixes https://github.com/pocoproject/poco/issues/2208

2023-12-05 15:31 UTC, soroshsabz commented
@aleks-f @matejk as you say, I create new PR, so please start CI

thanks

2023-12-06 01:58 UTC, aleks-f requested changes
we need only `vs_90`, `vs_160` and `vs_170` projects here (see #4274). all others should be deleted, and `vs_160` and `vs_170` generated with [progen](https://github.com/pocoproject/poco/wiki/Generating-VS-Projects-using-ProGen)

2024-02-02 18:35 UTC, geirhei commented
Any progress on this @soroshsabz? The library is very useful, would be great to get it into POCO.

2024-02-25 17:16 UTC, soroshsabz commented
@aleks-f I am done

please run CI

thanks

2024-02-25 17:16 UTC, soroshsabz commented
@matejk

2024-02-26 07:23 UTC, matejk commented
I don't know why only a few of the CI jobs were executed and not all of them.

2024-02-28 11:16 UTC, aleks-f commented on DNSSD/Bonjour/Bonjour_vs100.vcxproj
> +<?xml version="1.0" encoding="UTF-8"?>
bonjour old vs projects should be removed and vs160/170 created

2024-02-28 11:17 UTC, aleks-f commented on DNSSD/samples/DNSSDBrowser/DNSSDBrowser_WEC2013_vs120.vcxproj.filters
> +﻿<?xml version="1.0" encoding="utf-8"?>
samples old vs projects should be removed and vs160/170 created

2024-02-28 11:19 UTC, aleks-f commented on ActiveRecord/ActiveRecord_vs170.vcxproj
> +    <_ProjectFileVersion>17.0.34511.75</_ProjectFileVersion>
seems like we're going backwards here? there is no reason to modify other vs projects in this PR

2024-02-28 11:22 UTC, aleks-f commented on DNSSD/DNSSD_vs90.vcproj
> +<?xml version="1.0" encoding="Windows-1252"?>
only *_vs90.vcproj is needed, other vs90 files should be removed

2024-02-29 09:47 UTC, soroshsabz commented
@aleks-f I resolve all your notes

please run CI

2024-03-01 09:54 UTC, closed without merging

2024-03-01 09:54 UTC, aleks-f commented
#4479

2024-03-28 10:05 UTC, soroshsabz commented
@aleks-f 

I am happy to merge that PR

thanks