(fix #4536) SQLite transaction isolation support
pocoproject/poco pull request #4578
Opened 2024-06-07 13:01 UTC by bas524

I've add transaction isolation support for SQLite
Warning! SQLite transactions are [serializable by design](https:// www.sqlite.org/isolation.html) my implementation retuns ```false``` in function ```hasTransactionIsolation``` and throw an exception in ```setTransactionIsolation```

2024-06-21 09:25 UTC, bas524 commented on Data/SQLite/src/SessionImpl.cpp
> +	}
transaction type is integral by design

2024-06-21 09:25 UTC, bas524 commented on Data/SQLite/src/SessionImpl.cpp
> +	}
transaction type is integral by design

2024-09-11 18:16 UTC, aleks-f requested changes

2024-09-11 18:16 UTC, aleks-f commented on Data/SQLite/include/Poco/Data/SQLite/SessionImpl.h
> +		/// For ex. Two connections on the same thread with TRANSACTION_READ_UNCOMMITTED for only for one connection will throw exception "databse is locked"
please tidy up this comment, use `eg.` instead of `For ex.`, fix spelling errors and it is overall not quite clear what it is saying

2024-09-15 16:03 UTC, aleks-f commented
#4693

2024-09-15 16:03 UTC, closed without merging