Dependencies update
pocoproject/poco pull request #4607
Opened 2024-07-21 13:59 UTC by OgreTransporter

- Upgrade bundled SQLite to 3.46.0
- Upgrade bundled zlib to 1.3.1 (see #4582)
- Upgrade bundled libpng to 1.6.43 (see #4582)
- Upgrade bundled pcre2 to 10.44 (see #4478)

2024-07-24 08:24 UTC, aleks-f requested changes
for some reason, the PR CI is not triggered, but the last commit CI fails massively, please se why

2024-07-25 07:35 UTC, OgreTransporter commented
I have already created the fix 6a311fd, but it did not repeat the complete action. Can you trigger this manually?

2024-07-29 10:35 UTC, aleks-f requested changes
windows build fails

2024-07-29 15:47 UTC, matejk commented on PDF/CMakeLists.txt
> +    src/pngwutil.c
Unnecessary change of white space (tabs to spaces).

Is the list of source file shorter by three files intentionally or by accident?

2024-08-17 13:43 UTC, aleks-f commented
@OgreTransporter you have some CI failing

2024-09-12 06:16 UTC, closed without merging

2024-09-12 06:16 UTC, matejk commented
Replaced with #4676, #4677, #4678