Fixed incorrect SSL_CTX_set0_tmp_dh_pkey() usage
pocoproject/poco pull request #4663
Opened 2024-09-04 14:53 UTC by pkl97

This simple program crashes POCO (tested under Red Hat Enterprise Linux 9.4):

```c++
#include <Poco/Net/Context.h>

int main()
{
    const Poco::Net::Context context(Poco::Net::Context::CLIENT_USE, "/tmp", Poco::Net::Context::VERIFY_STRICT, 9, false, "ALL");
    return 0;
}
```

The problem is an incorrect usage of SSL_CTX_set0_tmp_dh_pkey() in Context::initDH(). The return value is not evaluated and the key is freed even if it has been successfully transferred to the SSL Context.

The relevant part of the OpenSSL manpage https://docs.openssl.org/3.1/man3/SSL_CTX_set_tmp_dh_callback/:

> Ownership of the dhpkey value is passed to the SSL_CTX or SSL object as a result of this call, and so the caller should not free it if the function call is successful.

2024-09-11 18:19 UTC, aleks-f requested changes
well, you broke quite a bit of things with this, please see what else needs to be adressed; won't be merged unless CI is all green

2024-09-23 14:48 UTC, chrisse74 commented
Hi all,

The error messages show that the newly introduced exception which is raised if SSL_CTX_set0_tmp_dh_pkey() returns with an error is triggering the failures in the CI.

> 1: CppUnit::TestCaller<HTTPSClientSessionTest>.testGetSmall
>     "Poco::Net::SSLContextException:
> SSL context exception: Context::initDH():SSL_CTX_set0_tmp_dh_pkey()
> 
> error:0A00018A:SSL routines::dh key too small"

OpenSSL rejects the given DH key because it is too small. Prior to this PR this rejection was not reported, leaving the client under the impression that the given DH keys were accepted.

My guess is that the machines running the failing tests are configured to use SECLEVEL=2 (see https://stackoverflow.com/questions/61626206/what-could-cause-dh-key-too-small-error ) and thereby do not support 1024-bit DH keys.

These errors go away if you change dhUse2048Bits from false to true in
https://github.com/pocoproject/poco/blob/b6b1fec14f3966ca2cf2b862f607e4c00093c964/NetSSL_OpenSSL/src/Context.cpp#L48C2-L48C23 

@aleks-f  Could changing dhUse2048Bits in Context::Params::Params() be the way forward?

PS: On my machine this change brings the errors down to two errors (probably unrelated?)
```
There were 2 errors:
 1: CppUnit::TestCaller<HTTPSClientSessionTest>.testProxy
    "Poco::Net::HTTPException:
HTTP Exception: Cannot establish proxy connection: Forbidden"
    in "<unknown>", line -1
 2: CppUnit::TestCaller<HTTPSStreamFactoryTest>.testProxy
    "Poco::Net::HTTPException:
HTTP Exception: Cannot establish proxy connection: Forbidden"
    in "<unknown>", line -1
```

2024-10-03 09:27 UTC, aleks-f commented
> @aleks-f Could changing dhUse2048Bits in Context::Params::Params() be the way forward?

Yes, but let's introduce the default values as parameters to the `Params::Params()`. And the key size should really be [the group number,](https://www.watchguard.com/help/docs/help-center/en-US/Content/en-US/Fireware/bovpn/manual/diffie_hellman_c.html) rather than a simple boolean switch between 1024/2048
 
> PS: On my machine this change brings the errors down to two errors (probably unrelated?)

yes, unrelated

2024-10-31 01:12 UTC, aleks-f commented
moved to #4753

2024-10-31 01:12 UTC, closed without merging