fix(cmake): remove libatomic dependency
pocoproject/poco pull request #4811
Opened 2024-12-03 23:21 UTC by aleks-f

2024-12-04 08:43 UTC, matejk requested changes
Linking `libatomic` came in with a patch that Debian applies in their build system.

I think that it is only required on 32-bit platforms and not 64-bit. Most probably linking can be made private as well for `libatomic`.

2024-12-06 21:50 UTC, aleks-f commented
If there is a choice, I'd say better not to fail on current platforms, then fail for the sake of maintaining the old ones. `<atomic>` is 14 years old

2024-12-07 10:17 UTC, matejk approved these changes

2024-12-07 22:35 UTC, merged

2024-12-11 15:21 UTC, matejk commented
Cherry-picked to poco-1.14.1.